export { default as Cursor } from "./Cursor";
export { default as Navbar } from "./Navbar";
export { default as HeroSection } from "./HeroSection";
export { default as Marquee } from "./Marquee";
export { default as AboutSection } from "./AboutSection";
export { default as ProjectsSection } from "./ProjectsSection";
export { default as ExperienceSection } from "./ExperienceSection";
export { default as LinksSection } from "./LinksSection";
export { default as ContactSection } from "./ContactSection";
